version: '3.8'

services:
  insta-tor-app:
    build: .
    container_name: insta-tor-app
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=4200
    volumes:
      - ./:/app
      - ./tor_instances:/app/tor_instances
      - ./tor_logs:/app/tor_logs
    restart: unless-stopped
